name: landmark_assignment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio:
  bloc: ^7.0.0
  flutter_bloc: ^7.3.3
  pretty_dio_logger: ^1.4.0
  intl: any
  logger: ^2.5.0
  google_fonts: any
  connectivity_plus: ^6.1.4
  riverpod: ^2.6.1
  firebase_auth: ^5.5.3
  get_it: ^8.0.2
  injectable: ^2.5.0
  flutter_svg: ^2.1.0
  rxdart: ^0.28.0
  get: ^4.7.2
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  animations: ^2.0.11
  flutter_rating_bar: ^4.0.1
  loading_animation_widget: ^1.3.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  firebase_core:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.9.1
  injectable_generator: ^2.6.2




flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/animations/
    - assets/Illustration/
